---
version: '2'
services:
  db:
    image: postgres:9.4
    restart: always
    hostname: postgres
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgres/data
    ports:
      - 54320:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=emp